### ISSUE TITLE
Installation done through admin user is not available to non admin

### ISSUE THREAD

**Issue by Deepak-bansal** [joao-carloto/RF_Install_Script#3]
Installation done through admin user is not available to non admin.

**Comment by joao-carloto** [comment]
Hi Deepak, thanks for the input.

This script will rewrite the current user PATH environment variable and not the system PATH. 
That was was deliberate option. I agree that it might not be the best for everyone.
If you manually add the following paths to the system PATH it will probably fix it: ;c:\python27;c:\python27\Scripts;c:\Selenium Drivers

Please confirm that this was the only issue.

**Comment by Deepak-bansal** [comment]
Yeah, thanks for the input.
