### ISSUE TITLE
selChromeDriver for x86_64 points to a invalid web address

### ISSUE THREAD

**Issue by joaocfernandes** [joao-carloto/RF_Install_Script#5]
Hi João,

During a install on Ubuntu 14.04 64 bit , the install of chrome driver failed because the web server is returning an XML at that address. As consequence the Unzip tool fails.

Unziping the chromedriver to /usr/local/bin
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.

**Comment by joao-carloto** [comment]
Fixed by @joaocfernandes 
Closing.
